apiVersion: v1
kind: ConfigMap
metadata:
  name: studycoach-backend-configmap
data:
  config.yaml: |
    server:
      address:     ":8000"
      openapiPath: ""
      swaggerPath: ""

    logger:
      level:  "warning"
      stdout: true
      path:   "/app/logs"
