apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: studycoach

commonLabels:
  env: production
  app.kubernetes.io/env: production

resources:
  - ../../base
  - configmap.yaml
  - hpa.yaml
  - secret.yaml.example

patches:
  - path: deployment.yaml

