// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cron

import (
	"backend/api/cron"
)

type ControllerV1 struct{}

func NewV1() cron.ICronV1 {
	return &ControllerV1{}
}
