apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: studycoach
commonLabels:
  app: studycoach-backend
  app.kubernetes.io/name: studycoach-backend
  app.kubernetes.io/part-of: studycoach
resources:
- namespace.yaml
- deployment.yaml
- service.yaml

