// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package regular_update

import (
	"backend/api/regular_update"
)

type ControllerV1 struct{}

func NewV1() regular_update.IRegularUpdateV1 {
	return &ControllerV1{}
}
