// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cron_execute

import (
	"backend/api/cron_execute"
)

type ControllerV1 struct{}

func NewV1() cron_execute.ICronExecuteV1 {
	return &ControllerV1{}
}
