// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalConversationsDao is internal type for wrapping internal DAO implements.
type internalConversationsDao = *internal.ConversationsDao

// conversationsDao is the data access object for table conversations.
// You can define custom methods on it to extend its functionality as you wish.
type conversationsDao struct {
	internalConversationsDao
}

var (
	// Conversations is globally public accessible object for table conversations operations.
	Conversations = conversationsDao{
		internal.NewConversationsDao(),
	}
)

// Fill with you ideas below.
