// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// cronExecuteDao is the data access object for the table cron_execute.
// You can define custom methods on it to extend its functionality as needed.
type cronExecuteDao struct {
	*internal.CronExecuteDao
}

var (
	// CronExecute is a globally accessible object for table cron_execute operations.
	CronExecute = cronExecuteDao{internal.NewCronExecuteDao()}
)

// Add your custom methods and functionality below.
