// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// cronLogDao is the data access object for the table cron_log.
// You can define custom methods on it to extend its functionality as needed.
type cronLogDao struct {
	*internal.CronLogDao
}

var (
	// CronLog is a globally accessible object for table cron_log operations.
	CronLog = cronLogDao{internal.NewCronLogDao()}
)

// Add your custom methods and functionality below.
