// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalDocumentVectorsDao is internal type for wrapping internal DAO implements.
type internalDocumentVectorsDao = *internal.DocumentVectorsDao

// documentVectorsDao is the data access object for table document_vectors.
// You can define custom methods on it to extend its functionality as you wish.
type documentVectorsDao struct {
	internalDocumentVectorsDao
}

var (
	// DocumentVectors is globally public accessible object for table document_vectors operations.
	DocumentVectors = documentVectorsDao{
		internal.NewDocumentVectorsDao(),
	}
)

// Fill with you ideas below.
