// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalKnowledgeBaseCronScheduleDao is internal type for wrapping internal DAO implements.
type internalKnowledgeBaseCronScheduleDao = *internal.KnowledgeBaseCronScheduleDao

// knowledgeBaseCronScheduleDao is the data access object for table knowledge_base_cron_schedule.
// You can define custom methods on it to extend its functionality as you wish.
type knowledgeBaseCronScheduleDao struct {
	internalKnowledgeBaseCronScheduleDao
}

var (
	// KnowledgeBaseCronSchedule is globally public accessible object for table knowledge_base_cron_schedule operations.
	KnowledgeBaseCronSchedule = knowledgeBaseCronScheduleDao{
		internal.NewKnowledgeBaseCronScheduleDao(),
	}
)

// Fill with you ideas below.
