// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalMessageAttachmentsDao is internal type for wrapping internal DAO implements.
type internalMessageAttachmentsDao = *internal.MessageAttachmentsDao

// messageAttachmentsDao is the data access object for table message_attachments.
// You can define custom methods on it to extend its functionality as you wish.
type messageAttachmentsDao struct {
	internalMessageAttachmentsDao
}

var (
	// MessageAttachments is globally public accessible object for table message_attachments operations.
	MessageAttachments = messageAttachmentsDao{
		internal.NewMessageAttachmentsDao(),
	}
)

// Fill with you ideas below.
