// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalUserSettingsDao is internal type for wrapping internal DAO implements.
type internalUserSettingsDao = *internal.UserSettingsDao

// userSettingsDao is the data access object for table user_settings.
// You can define custom methods on it to extend its functionality as you wish.
type userSettingsDao struct {
	internalUserSettingsDao
}

var (
	// UserSettings is globally public accessible object for table user_settings operations.
	UserSettings = userSettingsDao{
		internal.NewUserSettingsDao(),
	}
)

// Fill with you ideas below.
