apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: studycoach-develop

commonLabels:
  env: develop
  app.kubernetes.io/env: develop

resources:
- ../../base
- namespace.yaml
- configmap.yaml
- secret.yaml.example

patches:
- path: deployment.yaml

